=== Varbin/ausweiskopie/src/ausweiskopie/resources/schemas/document.json
{
  "$schema": "https://json-schema.org/draft-07/schema#",
  "$id": "https://schema.varb.in/in.varb.Ausweiskopie/document.json",
  "title": "Identity document description format",
  "type": "object",
  "required": [
    "id",
    "meta",
    "layout",
    "i18n"
  ],
  "properties": {
    "id": {
      "type": "string",
      "description": "Unique identifier of the document type and revision.",
      "format": "uuid"
    },
    "meta": {
      "type": "object",
      "description": "Metadata (Name, size, ...)",
      "properties": {
        "dimensions": {
          "default": "ID-1",
          "enum": [
            "ID-1",
            "ID-2",
            "ID-3",
            "CR-90",
            "custom"
          ],
          "type": "string",
          "description": "Standardized size of the card. Use ID-1 instead of CR80."
        },
        "dimensionsCustom": {
          "type": "array",
          "description": "Custom dimension (WxH) in mm.",
          "minItems": 2,
          "items": {
            "type": "number",
            "exclusiveMinimum": 0
          },
          "maxItems": 2
        },
        "issuer": {
          "minLength": 3,
          "maxLength": 3,
          "pattern": "[A-Z]{3}",
          "type": "string",
          "description": "Three letter ISO 3166-1 alpha-3 code of the issuing authority. Use the code included in passports for international organisations (e.g. Interpol, EU) or the nation state for documents issued by regional authorities (e.g. US states). Use DEU for Germany (not just D)."
        },
        "type": {
          "enum": [
            "id",
            "passport",
            "driving-permit",
            "laissez-passer",
            "residency-permit",
            "seafarer",
            "other"
          ],
          "type": "string",
          "description": "Document type."
        },
        "subtype": {
          "enum": [
            "temporary",
            "diplomatic",
            "service",
            "children",
            "other"
          ],
          "type": "string",
          "description": "Subtype of the document - a country may have different types of the same identity document."
        },
        "issuedSince": {
          "type": "string",
          "format": "date",
          "description": "When was this document type (and revision) first issued?"
        },
        "issuedUntil": {
          "type": "string",
          "format": "date",
          "description": "When was the last time this document was issued? Do not include if this document is still issued. Please not documents can be valid longer than this date."
        },
        "revision": {
          "type": "string",
          "description": "The official document revision by the issuer."
        },
        "mrz": {
          "enum": [
            "TD-1",
            "TD-2",
            "TD-3"
          ],
          "type": "string",
          "description": "Whether this document has an ICAO 9303 type MRZ."
        },
        "mrzId": {
          "type": "string",
          "description": "Beginning of the MRZ",
          "pattern": "[A-Z<]{5}"
        }
      },
      "required": [
        "dimensions",
        "issuer",
        "type",
        "issuedSince"
      ],
      "if": {
        "properties": {
          "dimensions": {
            "const": "other"
          }
        }
      },
      "then": {
        "required": [
          "dimensionsCustom"
        ]
      }
    },
    "layout": {
      "type": "object",
      "description": "Document sides",
      "properties": {
        "front": {
          "description": "Front side of the document.",
          "$ref": "#/$defs/fieldset"
        },
        "back": {
          "description": "Back side of the document. Passports usually have none.",
          "$ref": "#/$defs/fieldset"
        }
      },
      "required": [
        "front"
      ]
    },
    "i18n": {
      "type": "object",
      "description": "Official translation of documents.",
      "patternProperties": {
        "[A-Z][A-Z_]*": {
          "$ref": "#/$defs/translation"
        }
      },
      "additionalProperties": false,
      "required": [
        "DOCUMENT_NAME"
      ]
    }
  },
  "$defs": {
    "coordinate": {
      "type": "array",
      "minItems": 2,
      "maxItems": 2,
      "items": {
        "type": "number",
        "minimum": 0
      }
    },
    "rect": {
      "type": "object",
      "properties": {
        "tl": {
          "$ref": "#/$defs/coordinate"
        },
        "br": {
          "$ref": "#/$defs/coordinate"
        }
      },
      "additionalProperties": false,
      "required": [
        "tl",
        "br"
      ]
    },
    "field": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/rect"
      }
    },
    "translation": {
      "type": "object",
      "properties": {
        "en": {
          "type": "string"
        }
      },
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "en"
      ]
    },
    "fieldset": {
      "type": "object",
      "properties": {
        "DOCUMENT_NUMBER": {
          "$ref": "#/$defs/field"
        },
        "PHOTO": {
          "$ref": "#/$defs/field"
        },
        "SIGNATURE": {
          "$ref": "#/$defs/field"
        },
        "GIVEN_NAME": {
          "$ref": "#/$defs/field"
        },
        "SURNAME": {
          "$ref": "#/$defs/field"
        },
        "AUTHORITY": {
          "$ref": "#/$defs/field"
        },
        "NATIONALITY": {
          "$ref": "#/$defs/field"
        },
        "DATE": {
          "$ref": "#/$defs/field"
        },
        "DATE_OF_ISSUE": {
          "$ref": "#/$defs/field"
        },
        "DATE_OF_EXPIRY": {
          "$ref": "#/$defs/field"
        },
        "SEX": {
          "$ref": "#/$defs/field"
        },
        "DATE_OF_BIRTH": {
          "$ref": "#/$defs/field"
        },
        "PLACE_OF_BIRTH": {
          "$ref": "#/$defs/field"
        },
        "CAN": {
          "$ref": "#/$defs/field"
        },
        "MRZ": {
          "$ref": "#/$defs/field"
        }
      },
      "patternProperties": {
        "[A-Z][A-Z_]*": {
          "$ref": "#/$defs/field"
        }
      },
      "additionalProperties": false
    }
  }
}

=== Varbin/ausweiskopie/src/ausweiskopie/resources/documents/deu_id_temporary_2010-11-01.json
{
  "$schema": "https://schema.varb.in/in.varb.Ausweiskopie/document.json",
  "id": "becf99c3-a872-4765-adb5-89e5e8eb74c7",
  "meta": {
    "dimensions": "ID-2",
    "issuer": "DEU",
    "issuedSince": "2010-11-01",
    "type": "id",
    "subtype": "temporary",
    "mrz": "TD-2",
    "mrzId": "ITD<<"
  },
  "layout": {
    "front": {
      "DOCUMENT_NUMBER": [
        {
          "tl": [
            0.7583,
            0.18
          ],
          "br": [
            0.9664,
            0.25
          ]
        },
        {
          "tl": [
            0.04,
            0.867
          ],
          "br": [
            0.2462,
            0.93
          ]
        }
      ],
      "PHOTO": [
        {
          "tl": [
            0.0105,
            0.05
          ],
          "br": [
            0.2733,
            0.5525
          ]
        }
      ],
      "SURNAME": [
        {
          "tl": [
            0.2733,
            0.18
          ],
          "br": [
            0.753,
            0.235
          ]
        },
        {
          "tl": [
            0.04,
            0.804
          ],
          "br": [
            0.7795,
            0.867
          ]
        }
      ],
      "NAME_AT_BIRTH": [
        {
          "tl": [
            0.2733,
            0.235
          ],
          "br": [
            0.753,
            0.295
          ]
        }
      ],
      "GIVEN_NAME": [
        {
          "tl": [
            0.2733,
            0.3137
          ],
          "br": [
            0.9664,
            0.37
          ]
        },
        {
          "tl": [
            0.04,
            0.804
          ],
          "br": [
            0.7795,
            0.867
          ]
        }
      ],
      "DATE_OF_BIRTH": [
        {
          "tl": [
            0.2733,
            0.3861
          ],
          "br": [
            0.4693,
            0.445
          ]
        },
        {
          "tl": [
            0.3074,
            0.867
          ],
          "br": [
            0.4503,
            0.93
          ]
        }
      ],
      "PLACE_OF_BIRTH": [
        {
          "tl": [
            0.4693,
            0.3861
          ],
          "br": [
            0.9664,
            0.445
          ]
        }
      ],
      "NATIONALITY": [
        {
          "tl": [
            0.2773,
            0.4575
          ],
          "br": [
            0.4816,
            0.5125
          ]
        },
        {
          "tl": [
            0.2462,
            0.867
          ],
          "br": [
            0.3074,
            0.93
          ]
        }
      ],
      "HEIGHT": [
        {
          "tl": [
            0.5125,
            0.4575
          ],
          "br": [
            0.634,
            0.5125
          ]
        }
      ],
      "COLOUR_OF_EYES": [
        {
          "tl": [
            0.634,
            0.4575
          ],
          "br": [
            0.9664,
            0.5125
          ]
        }
      ],
      "ADDRESS": [
        {
          "tl": [
            0.2733,
            0.5289
          ],
          "br": [
            0.9664,
            0.5733
          ]
        }
      ],
      "DATE": [
        {
          "tl": [
            0.2733,
            0.5956
          ],
          "br": [
            0.6163,
            0.6428
          ]
        }
      ],
      "DATE_OF_EXPIRY": [
        {
          "tl": [
            0.6163,
            0.5959
          ],
          "br": [
            0.9644,
            0.6428
          ]
        },
        {
          "tl": [
            0.4714,
            0.867
          ],
          "br": [
            0.6136,
            0.93
          ]
        }
      ],
      "SIGNATURE": [
        {
          "tl": [
            0.2733,
            0.666
          ],
          "br": [
            0.9644,
            0.781
          ]
        }
      ],
      "MACHINE_READABLE_ZONE": [
        {
          "tl": [
            0.04,
            0.804
          ],
          "br": [
            0.7795,
            0.93
          ]
        }
      ]
    },
    "back": {
      "RELIGIOUS_NAME_OR_PSEUDONYM": [
        {
          "tl": [
            0.0723,
            0.225
          ],
          "br": [
            0.783,
            0.275
          ]
        }
      ],
      "AUTHORITY": [
        {
          "tl": [
            0.0723,
            0.4875
          ],
          "br": [
            0.783,
            0.5525
          ]
        }
      ]
    }
  },
  "i18n": {
    "DOCUMENT_NAME": {
      "en": "(Temporary) Identity Card",
      "de": "Vorläufiger Personalausweis",
      "fr": "Carte d'identité (temporaire)"
    },
    "SURNAME": {
      "en": "Surname",
      "de": "Name",
      "fr": "Nom"
    },
    "GIVEN_NAME": {
      "en": "Given names",
      "de": "Vornamen",
      "fr": "Prénoms"
    },
    "DATE_OF_BIRTH": {
      "en": "Date of birth",
      "de": "Geburtsdatum",
      "fr": "Date de naissance"
    },
    "PLACE_OF_BIRTH": {
      "en": "Place of birth",
      "de": "Geburtsort",
      "fr": "Lieu de naissance"
    },
    "NATIONALITY": {
      "en": "Nationality",
      "de": "Staatsangehörigkeit",
      "fr": "Nationalité"
    },
    "HEIGHT": {
      "en": "Height",
      "de": "Größe",
      "fr": "Taille"
    },
    "COLOUR_OF_EYES": {
      "en": "Colour of eyes",
      "de": "Augenfarbe",
      "fr": "Couleur des yeux"
    },
    "ADDRESS": {
      "en": "Address",
      "de": "Gegenwärtige Anschrift",
      "fr": "Adresse"
    },
    "DATE_OF_ISSUE": {
      "en": "Date of issue",
      "de": "Ausstellungsdatum",
      "fr": "Date de délivrance"
    },
    "DATE_OF_EXPIRY": {
      "en": "Date of expiry",
      "de": "Gültig bis",
      "fr": "Date d` expiration"
    },
    "SIGNATURE": {
      "en": "Signature of bearer",
      "de": "Unterschrift der Inhaberin/des Inhabers",
      "fr": "signature de la titulaire/du titulaire"
    },
    "AUTHORITY": {
      "en": "Authority",
      "de": "Behörde",
      "fr": "Autorité"
    },
    "RELIGIOUS_NAME_OR_PSEUDONYM": {
      "en": "Religious name or pseudonym",
      "de": "Ordens- oder Künstlername",
      "fr": "Nom de religion ou pseudonyme"
    }
  }
}
